const projects = [
  {name:'openpilot',repo:'commaai/openpilot',domain:'stack',domainLabel:'系统栈',icon:'OP',stars:61200,starLabel:'61.2k',freshness:6,updated:'发布：2026-03',desc:'真实车辆辅助驾驶系统的完整代码入口，能看见感知、驾驶策略、日志与车载接口如何在同一条数据链上协作。',fit:'想做端到端驾驶、真实车载数据流、CAN 接口或系统级误差分析。',start:'先读 README 和支持车型说明；建议从日志回放、模块边界与数据格式入手，先不做道路测试。',tags:['端到端','车载系统','日志'],url:'https://github.com/commaai/openpilot'},
  {name:'CARLA',repo:'carla-simulator/carla',domain:'simulation',domainLabel:'仿真验证',icon:'CA',stars:14400,starLabel:'14.4k',freshness:5,updated:'UE5 分支持续开发',desc:'面向自动驾驶研究的开源仿真器：可组合地图、交通参与者、天气、传感器和可控场景，特别适合闭环验证。',fit:'规划控制、强化学习、感知鲁棒性、场景生成与对比实验。',start:'先跑 Python API 的同步模式示例；固定随机种子与场景，再引入一个变量做对照。',tags:['闭环仿真','Python API','场景'],url:'https://github.com/carla-simulator/carla'},
  {name:'Autoware',repo:'autowarefoundation/autoware',domain:'stack',domainLabel:'系统栈',icon:'AW',stars:11700,starLabel:'11.7k',freshness:6,updated:'最新发布：2026-05',desc:'基于 ROS 2 的开源自动驾驶软件栈，把定位、感知、规划、控制与部署组织成工程化模块。',fit:'ROS 2、模块化规划控制、系统集成、数字孪生或论文原型落地。',start:'从官方 source-installation 与示例传感器套件开始；先画清 ROS topic 与坐标系，再替换一个模块。',tags:['ROS 2','规划控制','集成'],url:'https://github.com/autowarefoundation/autoware'},
  {name:'OpenPCDet',repo:'open-mmlab/OpenPCDet',domain:'perception',domainLabel:'3D 感知',icon:'3D',stars:5600,starLabel:'5.6k',freshness:4,updated:'社区 PR：2026-06',desc:'LiDAR 3D 检测的 PyTorch 工具箱，聚合 PointRCNN、PV-RCNN、Voxel R-CNN 等经典可比基线。',fit:'点云检测、KITTI / nuScenes / Waymo 对比、稀疏卷积和感知模型消融。',start:'先用官方预训练模型跑 demo；严格核对坐标系、数据转换和评估脚本，再改模型或损失。',tags:['点云','3D 检测','PyTorch'],url:'https://github.com/open-mmlab/OpenPCDet'},
  {name:'UniAD',repo:'OpenDriveLab/UniAD',domain:'research',domainLabel:'前沿研究',icon:'UA',stars:4700,starLabel:'4.7k',freshness:3,updated:'更新：2025-10',desc:'CVPR 2023 Best Paper 的规划导向统一自动驾驶框架，将感知、跟踪、预测、占据和规划放在一张研究图里。',fit:'多任务学习、BEV、规划导向指标、端到端自动驾驶论文复现。',start:'先把论文任务图画成输入—中间表示—指标；复现一个官方配置后只替换一个 task head。',tags:['BEV','多任务','规划'],url:'https://github.com/OpenDriveLab/UniAD'},
  {name:'Awesome Autonomous Driving',repo:'autonomousdrivingkr/Awesome-Autonomous-Driving',domain:'research',domainLabel:'研究雷达',icon:'AD',stars:610,starLabel:'610',freshness:5,updated:'内容刷新：2026-07',desc:'不是代码基线，而是一份持续整理的文献、数据集、基准与课程雷达；最近补充了 VLA、世界模型与闭环评测。',fit:'开题选题、综述写作、追踪端到端 / 世界模型 / benchmark 的新方向。',start:'按主题建一个 Zotero 文件夹；每周只挑 2 篇论文，顺着其官方代码与 benchmark 反查证据。',tags:['文献雷达','Benchmark','综述'],url:'https://github.com/autonomousdrivingkr/Awesome-Autonomous-Driving'}
];
const grid=document.querySelector('#project-grid'),empty=document.querySelector('#empty-state'),search=document.querySelector('#search'),sort=document.querySelector('#sort');let currentFilter='all';
function card(p){const tags=p.tags.map(function(t){return '<span class="skill-tag">'+t+'</span>'}).join('');return '<article class="project-card"><div class="card-top"><span class="repo-icon">'+p.icon+'</span><div class="card-meta"><span class="tag">'+p.domainLabel+'</span><small>'+p.updated+'</small></div></div><h3>'+p.name+'</h3><p class="card-desc">'+p.desc+'</p><div class="guidance"><p><b>适用于</b>'+p.fit+'</p><p><b>怎么用</b>'+p.start+'</p></div><div class="meta"><span class="stars"><i>★</i> '+p.starLabel+'</span><div class="skill-tags">'+tags+'</div></div><a class="card-link" href="'+p.url+'" target="_blank" rel="noreferrer">'+p.repo+' <span>↗</span></a></article>'}
function render(){const q=search.value.trim().toLowerCase();const list=projects.filter(function(p){return (currentFilter==='all'||p.domain===currentFilter)&&(!q||[p.name,p.repo,p.desc,p.fit,p.start].concat(p.tags).join(' ').toLowerCase().includes(q))});list.sort(function(a,b){if(sort.value==='stars')return b.stars-a.stars;if(sort.value==='name')return a.name.localeCompare(b.name);return b.freshness-a.freshness||b.stars-a.stars});empty.hidden=list.length>0;grid.innerHTML=list.map(card).join('')}
document.querySelectorAll('.filter').forEach(function(button){button.addEventListener('click',function(){document.querySelector('.filter.active').classList.remove('active');button.classList.add('active');currentFilter=button.dataset.filter;render()})});search.addEventListener('input',render);sort.addEventListener('change',render);render();
